
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { useState } from "react";
import { AppWrapper } from "@/contexts/UserContext";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        {/* Add any necessary meta tags, title, stylesheets, etc. */}
        <title>Blitz Shop Admin</title>
      </head>
      <body className={inter.className}>
      <AppWrapper>
        <Navbar />
        {children}
        <Footer />
        <Toaster />
      </AppWrapper>
      
      </body>
    </html>
  );
}
